// Datos importados desde Libro1sadsa.xlsx (hoja bbdd)
// Responsable asignado en rotación equitativa entre las 7 personas

const AVANCE_RECORDS = [
{
"idx": 1,
"rut": "5776007-9",
"candidato": "JORGE OSVALDO MUÑOZ OYARCE",
"eleccion": "GORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "370-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 2,
"rut": "11804863-6",
"candidato": "JORGE PATRICIO ABELLO MOLL",
"eleccion": "GORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "385-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 3,
"rut": "12804003-K",
"candidato": "FELIPE RIOS CUEVAS",
"eleccion": "GORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "395-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 4,
"rut": "11789420-7",
"candidato": "LUCIANO ERNESTO SILVA MORA",
"eleccion": "GORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "390-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 5,
"rut": "13231848-4",
"candidato": "MARIA JOSE HOFFMANN OPAZO",
"eleccion": "GORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "457-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 6,
"rut": "13247123-1",
"candidato": "JUAN JALET HISI ESPINOZA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "628-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 7,
"rut": "12437024-8",
"candidato": "PAOLA AMANDA DEBIA GONZALEZ",
"eleccion": "GORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "393-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 8,
"rut": "10516539-0",
"candidato": "IRENIO SEGUNDO MONTECINOS HENRIQUEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "576-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 9,
"rut": "10586852-9",
"candidato": "GINO CURTI EMBRY",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "986-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 10,
"rut": "17265138-0",
"candidato": "IGNACIO ALVAREZ VERA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "836-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 11,
"rut": "10514344-3",
"candidato": "RAUL ERNESTO SAUVAGEOT DIAZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1017-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 12,
"rut": "10832808-8",
"candidato": "CRISTIAN ANDRES VELIZ SOLIS",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "958-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 13,
"rut": "17872160-7",
"candidato": "FERNANDA ISABEL GONZALEZ VIVANCO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "357-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 14,
"rut": "11224708-4",
"candidato": "FABIAN EDMUNDO RODRIGUEZ RIVERA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "943-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 15,
"rut": "10881159-5",
"candidato": "HECTOR RENE CARRASCO RUIZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "962-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 16,
"rut": "13739040-K",
"candidato": "JESSICA BEATRIZ DROPPELMANN ROSAS",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "924-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 17,
"rut": "11942205-1",
"candidato": "MARIELA AMAYA DONOSO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "859-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 18,
"rut": "6740137-9",
"candidato": "JULIO ANTONIO CHERIF PEREZ",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1002-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 19,
"rut": "10709896-8",
"candidato": "JASMINA DEL CARMEN VALENZUELA REYES",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "998-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 20,
"rut": "6778475-8",
"candidato": "OSCIEL VELASQUEZ HERNANDEZ",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "973-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 21,
"rut": "6697352-2",
"candidato": "PEDRO RAMON PARRAGUEZ GOMEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "996-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 22,
"rut": "6591781-5",
"candidato": "JUAN CARLOS HINOJOSA ESPEJO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "991-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 23,
"rut": "11245639-2",
"candidato": "HERNAN PATRICIO CALBUÑIR MILCHIO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "914-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 24,
"rut": "10960487-9",
"candidato": "ELVIRA ELIZABETH SOTO ORELLANA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "953-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 25,
"rut": "10909917-1",
"candidato": "OLIVIA ELENA TORRES GOMEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "947-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 26,
"rut": "4102661-8",
"candidato": "JOSE PABLO DONOSO URZUA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1232-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 27,
"rut": "10172281-3",
"candidato": "RENE GARCES ALVAREZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1301-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 28,
"rut": "16477301-9",
"candidato": "SEBASTIAN FUENTES GALLARDO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "972-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 29,
"rut": "15260476-9",
"candidato": "REMIGIO SANTIAGO HUENOLAF HUIRCALAF",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1203-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 30,
"rut": "5069199-3",
"candidato": "MANUEL LUIS HUMBERTO DIAZ VASQUEZ",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1234-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 31,
"rut": "10435851-9",
"candidato": "XIMENA BERNAL GONZALEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1065-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 32,
"rut": "10456676-6",
"candidato": "ANTONIO VALENTIN GALVEZ POBLETE",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1071-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 33,
"rut": "15921198-3",
"candidato": "GABRIEL SEBASTIAN TIZNADO ZURITA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1050-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 34,
"rut": "16020159-2",
"candidato": "AYLYNE VICENCIO MORENO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1072-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 35,
"rut": "5949179-2",
"candidato": "GASTON FERNANDEZ MORI",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1037-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 36,
"rut": "10025170-1",
"candidato": "MARIO ENRIQUE BARRUETO GAJARDO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1126-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 37,
"rut": "10193983-9",
"candidato": "MIGUEL ANGEL SALGADO MUÑOZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1099-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 38,
"rut": "13350327-7",
"candidato": "MILIPZA GABRIELA FARIAS QUIJADA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1121-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 39,
"rut": "15943456-7",
"candidato": "OSCAR ARMANDO MACIAS BORQUEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1056-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 40,
"rut": "13387738-K",
"candidato": "YESSICA FLORES CEA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1091-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 41,
"rut": "15306907-7",
"candidato": "ANGELA DANIELA BARRIA BARRIENTOS",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1208-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 42,
"rut": "10089731-8",
"candidato": "ALEJANDRA VILLEGAS HUICHAMAN",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1093-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 43,
"rut": "6848120-1",
"candidato": "MARIA CRISTINA CONCHA WAGENKNECHT",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "960-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 44,
"rut": "9539207-5",
"candidato": "EDWIN ALFONSO PERRETT ROJAS",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1142-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 45,
"rut": "16645089-6",
"candidato": "ENRIQUE ALFONSO DEL BARRIO HERNANDEZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "930-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 46,
"rut": "13403709-1",
"candidato": "MARCO ANTONIO CARRILLO BRAVO",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1040-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 47,
"rut": "9457718-7",
"candidato": "MARIA ALEJANDRA OLIVARES PONCE",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1190-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 48,
"rut": "15575753-1",
"candidato": "MIGUEL ANGEL GODOY NORIEGA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1162-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 49,
"rut": "15820031-7",
"candidato": "NEHEL ENRIQUE MUÑOZ LAGOS",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1220-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 50,
"rut": "6720037-3",
"candidato": "CARLOS ALBERTO MELLA LATORRE",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1251-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 51,
"rut": "11278970-7",
"candidato": "CRISTINA IVONNE MARCHANT SALINAS",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1355-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 52,
"rut": "11469922-5",
"candidato": "ANALIZ XIMENA VEGA CERDA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1363-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 53,
"rut": "10909749-7",
"candidato": "CARLOS FERNANDO ACEVEDO CIFUENTES",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1347-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 54,
"rut": "10457817-9",
"candidato": "JUAN MUÑOZ QUEZADA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1320-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 55,
"rut": "9379595-4",
"candidato": "ELIANA ELENA AZOCAR SILVA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1281-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 56,
"rut": "10190076-2",
"candidato": "IVONNE RIVAS ORTIZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1309-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 57,
"rut": "11186445-4",
"candidato": "WILDO RICHARD FARIAS GONZALEZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1356-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 58,
"rut": "9178201-4",
"candidato": "JUAN JESUS HERRERA FUENTES",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1276-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 59,
"rut": "10135145-9",
"candidato": "ITALO MARTINEZ CARVALLO",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1297-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 60,
"rut": "9239412-3",
"candidato": "MARCELO PATRICIO VARGAS MARTINEZ",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1277-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 61,
"rut": "10596717-9",
"candidato": "MONICA NAVARRO BUSTAMANTE",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1330-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 62,
"rut": "15604235-8",
"candidato": "LEONARDO BRUNO CONTRERAS NEIRA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1560-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 63,
"rut": "9774341-K",
"candidato": "JOSE BRAVO BURGOS",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1286-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 64,
"rut": "8901892-7",
"candidato": "NIVIA DEL CARMEN RIQUELME GUTIERREZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1270-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 65,
"rut": "13693016-8",
"candidato": "MAXIMILIANO ESTEBAN AVILES MARAMBIO",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1471-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 66,
"rut": "16481179-4",
"candidato": "ISMAEL ENRIQUE SAN MARTIN AGUILERA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1371-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 67,
"rut": "15876604-3",
"candidato": "LUIS MIGUEL CEBALLOS MERIÑO",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1036-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 68,
"rut": "9619738-1",
"candidato": "ROSA ELIANA NABALON SALAZAR",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1154-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 69,
"rut": "9197574-2",
"candidato": "CARLOS PATRICIO CAMPUSANO CERDA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1197-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 70,
"rut": "9110343-5",
"candidato": "WILMA JIMENEZ MUTIS",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1191-2025",
"oficio": "NO",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 71,
"rut": "14054125-7",
"candidato": "VIVIANA DEL PILAR RAMIREZ MELENDEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "799-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 72,
"rut": "15510976-9",
"candidato": "YERSON ANDRES SOTO VENEGAS",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1173-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 73,
"rut": "17029781-4",
"candidato": "CONSTANZA GABRIELA SCHONHAUT SOTO",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1547-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 74,
"rut": "16367003-8",
"candidato": "FELIPE ROSS CORREA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "979-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 75,
"rut": "16522749-2",
"candidato": "GUIDO CARREÑO REYES",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "570-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 76,
"rut": "4665425-0",
"candidato": "CARLOS ESCOBAR PAREDES",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1233-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 77,
"rut": "15930807-3",
"candidato": "FELIPE MUÑOZ HEREDIA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1053-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 78,
"rut": "12378443-K",
"candidato": "ALDO GUSTAVO SANDOVAL GARRIDO",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1405-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 79,
"rut": "12640104-3",
"candidato": "CLAUDIA ACEVEDO CORNEJO",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1413-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 80,
"rut": "7263887-5",
"candidato": "PASCUAL SEGUNDO AREVALOS MARTINEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "857-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 81,
"rut": "17339423-3",
"candidato": "PRISCILA ESTEFANY REYES TRONCOSO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "828-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 82,
"rut": "16051085-4",
"candidato": "LISETTE ARELLANO SANCHEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1077-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 83,
"rut": "6857246-0",
"candidato": "NELLY RAQUEL SANTANDER MARIN",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "966-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 84,
"rut": "12522490-3",
"candidato": "ERNA MARJORIE MALDONADO CASANOVA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "750-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 85,
"rut": "17213474-2",
"candidato": "GABRIEL FRANCISCO ACUÑA VASQUEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "863-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 86,
"rut": "16246810-3",
"candidato": "GLEICY DE LOS ANGELES BERGEN LOYOLA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1030-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 87,
"rut": "12271034-3",
"candidato": "CAROLINA ANDREA PRIETO NUÑEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "797-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 88,
"rut": "17741002-0",
"candidato": "GONZALO IGNACIO AGUAYO GAJARDO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "804-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 89,
"rut": "15312160-5",
"candidato": "FELIPE ILLANES DIEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1211-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 90,
"rut": "11838331-1",
"candidato": "ROSARIO DEL CARMEN CARVAJAL ARAYA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1152-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 91,
"rut": "11744268-3",
"candidato": "CAROLA GONZALEZ INOSTROZA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1372-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 92,
"rut": "7313423-4",
"candidato": "CARLOS FLORES GONZALEZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1258-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 93,
"rut": "16256359-9",
"candidato": "PRISSILA NATALY FARIAS MORALES",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1227-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 94,
"rut": "13389115-3",
"candidato": "ALEJANDRA BURGOS BIZAMA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "499-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 95,
"rut": "11932476-9",
"candidato": "DINKA SOLANGE LOPEZ DURAN",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1379-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 96,
"rut": "17129616-1",
"candidato": "DANIEL MENA GUAJARDO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1457-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 97,
"rut": "17248502-2",
"candidato": "CAMILA TORRES UMANZOR",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1561-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 98,
"rut": "17647509-9",
"candidato": "ANGELO MAURICIO MILLAMAN LOPEZ",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1580-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 99,
"rut": "9494187-3",
"candidato": "JORGE ALBERTO SUAREZ SUAREZ",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1554-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "EN REDACCION"
},
{
"idx": 100,
"rut": "10995136-6",
"candidato": "JORGE BRUNO KEIM GUTIERREZ",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1354-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 101,
"rut": "10238592-6",
"candidato": "FERMIN ALEJANDRO CARREÑO CARREÑO",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1313-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 102,
"rut": "13209722-4",
"candidato": "JORGE LUIS URZUA GARCIA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1444-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 103,
"rut": "16279870-7",
"candidato": "CYNTHIA ACUÑA SILVA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1507-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 104,
"rut": "7371986-0",
"candidato": "JAVIER HERNANDEZ HERNANDEZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1149-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 105,
"rut": "10397759-2",
"candidato": "JUAN ELVIRO CARRASCO CONTRERAS",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1321-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 106,
"rut": "11993445-1",
"candidato": "JUAN CARLOS ZURITA MEDINA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1386-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 107,
"rut": "13429418-3",
"candidato": "KATYHUSKA POLONSKY ROBLERO",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1458-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 108,
"rut": "7077432-1",
"candidato": "SADI MELO MOYA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "524-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 109,
"rut": "13831881-8",
"candidato": "SANDRA DANIELA BELTRAMI MONTERO",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "900-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 110,
"rut": "10603731-0",
"candidato": "OMAR NORAMBUENA RIVERA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1335-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "EN REDACCION"
},
{
"idx": 111,
"rut": "10202947-K",
"candidato": "FERNANDO RODRIGO CONTRERAS BOISIER",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1101-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 112,
"rut": "12479478-1",
"candidato": "CLAUDIA ANDREA ATENAS SOZA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1410-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 113,
"rut": "11736760-6",
"candidato": "KARIN LUCK URBAN",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1368-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 114,
"rut": "15248646-4",
"candidato": "LUCIANO RIVAS STEPKE",
"eleccion": "GORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "420-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 115,
"rut": "9315641-2",
"candidato": "REBECA DEL ROSARIO COFRE CALDERON",
"eleccion": "GORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "374-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 116,
"rut": "10674551-K",
"candidato": "RODRIGO MAURICIO AGUILERA BOIN",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1463-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 117,
"rut": "13014655-4",
"candidato": "YERKO FABIAN CHAMORRO SIGDMAN",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1429-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 118,
"rut": "9402368-8",
"candidato": "RODRIGO CORNEJO INOSTROZA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1284-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 119,
"rut": "12354743-8",
"candidato": "HORTENSIA MORA CATALAN",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1406-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 120,
"rut": "13979658-6",
"candidato": "CLAUDIA ADASME DONOSO",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1480-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 121,
"rut": "14472502-6",
"candidato": "ROXANA RIQUELME TABACH",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1492-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 122,
"rut": "13907387-8",
"candidato": "PAULINA REBECA BOBADILLA NAVARRETE",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1477-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 123,
"rut": "6147873-6",
"candidato": "LUIS ALBERTO COULON LOPEZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1043-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 124,
"rut": "12785136-0",
"candidato": "ANA PAOLA PONCE ROJAS",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1424-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 125,
"rut": "9214318-K",
"candidato": "SERGIO RIGOBERTO ECHEVERRIA GARCIA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1179-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 126,
"rut": "8993729-9",
"candidato": "JOHNNSON GUIÑEZ NUÑEZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1274-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 127,
"rut": "13368689-4",
"candidato": "JOSE MORAGA LIRA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1446-2025",
"oficio": "NO",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 128,
"rut": "14402401-K",
"candidato": "EDUARDO URIBE CAMPOS",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1490-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 129,
"rut": "14094805-5",
"candidato": "MARIA CRISTINA PAINEMAL PAINEMAL",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1483-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 130,
"rut": "15291284-6",
"candidato": "OSCAR ARISTIDES GALLARDO CALBUYAHUE",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1495-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "EN REDACCION"
},
{
"idx": 131,
"rut": "16090622-7",
"candidato": "GABRIEL ROJAS ROJAS",
"eleccion": "GORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "415-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 132,
"rut": "17173447-9",
"candidato": "KAREN ANDREA GOMEZ GOMEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "858-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 133,
"rut": "18313008-0",
"candidato": "DENISSE ANDREA MORALES FLORES",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1592-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 134,
"rut": "15129422-7",
"candidato": "CRISTIAN FERNANDEZ MUÑOZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1623-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 135,
"rut": "15126001-2",
"candidato": "JUAN CARLOS ABUD PARRA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1494-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 136,
"rut": "13325647-4",
"candidato": "JESSICA RUTH BARRIENTOS BARRIENTOS",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1135-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 137,
"rut": "10606628-0",
"candidato": "MAURICIO HENRIQUEZ SANDOVAL",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "989-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 138,
"rut": "20300175-4",
"candidato": "LILITH VICTORIA ATENEA TRUJILLO ESPINOZA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1613-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 139,
"rut": "13972541-7",
"candidato": "JORGE MORALES SANHUEZA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1479-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 140,
"rut": "17933717-7",
"candidato": "ANDREA NICOLE ACUÑA MUÑOZ",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1587-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 141,
"rut": "17826151-7",
"candidato": "CRISTOBAL BRAVO VALENZUELA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1583-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 142,
"rut": "16349651-8",
"candidato": "LUIS DOMINGO MILLA RAMIREZ",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1542-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 143,
"rut": "17275627-1",
"candidato": "JOSE ERNESTO MACHUCA TORRES",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1557-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 144,
"rut": "16724912-4",
"candidato": "SEBASTIAN NICOLAS GODOY LEAL",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1521-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 145,
"rut": "13223572-4",
"candidato": "ALEJANDRO CAMPUSANO MASSAD",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1687-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 146,
"rut": "18900254-8",
"candidato": "BAIRON MANUEL ARANCIBIA ROJAS",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1598-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 147,
"rut": "8280140-5",
"candidato": "ALEJANDRO FIDEL MORALES IMAÑA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1559-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 148,
"rut": "11846601-2",
"candidato": "MAURICIO ALEJANDRO ROSEN FUENTEALBA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "355-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 149,
"rut": "18535046-0",
"candidato": "FELIPE IGNACIO FARIAS LOPEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1680-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 150,
"rut": "9852172-0",
"candidato": "CARLOS AUGUSTO CASTRO VIDAL",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1140-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 151,
"rut": "12607560-K",
"candidato": "ELIECER DANIEL CHAMORRO VARGAS",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1412-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 152,
"rut": "12135667-8",
"candidato": "OSVALDO CARTAGENA GARCIA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1389-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 153,
"rut": "9856751-8",
"candidato": "JAMES FRY CAREY",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1288-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 154,
"rut": "10968897-5",
"candidato": "CAROLINA CORTI BADIA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1346-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 155,
"rut": "15630966-4",
"candidato": "OSVALDO JORQUERA PADILLA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1500-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 156,
"rut": "15032285-5",
"candidato": "JONATHAN ALFREDO CARMONA DIAZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1563-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 157,
"rut": "12599094-0",
"candidato": "VICTOR DONOSO OYANEDEL",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1409-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 158,
"rut": "18464777-K",
"candidato": "DIEGO RAMIREZ DONOSO",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1591-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 159,
"rut": "16975775-5",
"candidato": "PABLO ANDRES GUGLIELMI ASENJO",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1537-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 160,
"rut": "14183177-1",
"candidato": "CRISTIAN ENRIQUE BARRENECHEA RIVERA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "727-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 161,
"rut": "17529378-7",
"candidato": "MATIAS SEBASTIAN AVENDAÑO RAGGI",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1574-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 162,
"rut": "16991905-4",
"candidato": "FERNANDO MARCELO ASTORGA TERRAZA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1545-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 163,
"rut": "7689686-0",
"candidato": "VERONICA DEL CARMEN ROJAS ARENAS",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1567-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 164,
"rut": "16940608-1",
"candidato": "SVEN VON MUHLENBROCK SCHLATTER",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1531-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 165,
"rut": "17993305-5",
"candidato": "MACARENA CAROLINA RIPAMONTI SERRANO",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "752-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 166,
"rut": "14052917-6",
"candidato": "LUZMIRA ELIZABETH ALBORNOZ JIMENEZ",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1550-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 167,
"rut": "16097475-3",
"candidato": "ALVARO BELLOLIO AVARIA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1742-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 168,
"rut": "16895750-5",
"candidato": "CRISTIAN ALEJANDRO AVENDAÑO ZARATE",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1527-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 169,
"rut": "16732417-7",
"candidato": "BORIS BENJAMIN CARVAJAL TAPIA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "917-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 170,
"rut": "9524536-6",
"candidato": "SILVIA TEOFILA RIVERA VALDIVIA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1671-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 171,
"rut": "12039744-3",
"candidato": "MARCELO MAURICIO ESPINOZA ARIAS",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1383-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 172,
"rut": "18567078-3",
"candidato": "ALICIA PURISIMA ELOISA YEVENES AHUMADA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1595-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 173,
"rut": "8252230-1",
"candidato": "VILMA DE LOURDES ESQUIVEL CESPEDES",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1716-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 174,
"rut": "14120679-6",
"candidato": "JORGE ANDRES ZILLERUELO FERNANDEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1718-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 175,
"rut": "7642879-4",
"candidato": "JORGE ANTONIO VALDOVINOS GOMEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1722-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 176,
"rut": "15841371-K",
"candidato": "DANIELA SAN MARTIN PIZARRO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1676-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 177,
"rut": "12171878-2",
"candidato": "GENARO BRICEÑO TAPIA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1396-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "EN REDACCION"
},
{
"idx": 178,
"rut": "15061633-6",
"candidato": "DINA PATRICIA GONZALEZ ALFARO",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1711-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 179,
"rut": "13571632-4",
"candidato": "CARLOS CARRERO PEREZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1464-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 180,
"rut": "20340775-0",
"candidato": "ALI MANOUCHEHRI MOGHADAM KASHAN LOBOS",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1541-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 181,
"rut": "16340210-6",
"candidato": "LUIS MOISES CORTES IBARRA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1512-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 182,
"rut": "16632344-4",
"candidato": "LUIS CAMILO ERICES QUEZADA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1520-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 183,
"rut": "9688137-1",
"candidato": "RODOLFO BAIER ESTEBAN",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1566-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 184,
"rut": "17438560-2",
"candidato": "DIEGO FERNANDEZ SOTO",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1565-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 185,
"rut": "17534867-0",
"candidato": "VIVIANA AVILA SILVA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1573-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 186,
"rut": "17706105-0",
"candidato": "DANIELA CONSTANZA PARADA VARGAS",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1579-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 187,
"rut": "7422130-0",
"candidato": "JUAN EDUARDO RIQUELME VENEGAS",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1659-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 188,
"rut": "19828975-2",
"candidato": "DIEGO ANDRES VERGARA PEREZ",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1607-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "EN REDACCION"
},
{
"idx": 189,
"rut": "20236965-0",
"candidato": "GABRIEL PABLO FLORES CANALES",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1610-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "EN REDACCION"
},
{
"idx": 190,
"rut": "10661315-K",
"candidato": "CLAUDIO ABRAHAM CUMSILLE CHOMALI",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1337-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 191,
"rut": "7449057-3",
"candidato": "ERICA DEL PILAR LOPEZ SOTO",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1662-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "EN REDACCION"
},
{
"idx": 192,
"rut": "9421421-1",
"candidato": "LEONARDO BORQUEZ CASTILLO",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1648-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 193,
"rut": "8740279-7",
"candidato": "HILDA SOLEDAD GALLARDO VASQUEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1618-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 194,
"rut": "8856464-2",
"candidato": "CARLOS FRANCISCO RAMIREZ PEREZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1629-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 195,
"rut": "15061591-7",
"candidato": "KAREN ALEJANDRA BERRIOS GUERRA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1622-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 196,
"rut": "8905584-9",
"candidato": "HECTOR RODRIGO SILVA TAPIA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1643-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 197,
"rut": "6289845-3",
"candidato": "ISABEL MARGARITA GARCES URETA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1758-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 198,
"rut": "12610313-1",
"candidato": "LORENA DEL PILAR VENTURA VASQUEZ",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1759-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 199,
"rut": "17433740-3",
"candidato": "JUAN SALVADOR RODRIGUEZ BRAHM",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1750-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 200,
"rut": "17559293-8",
"candidato": "ESTEBAN HERNAN BARAHONA CONTRERAS",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1578-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 201,
"rut": "8809442-5",
"candidato": "PAULA DOMINGUEZ RISOPATRON",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1720-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "EN REDACCION"
},
{
"idx": 202,
"rut": "16609644-8",
"candidato": "CRISTINA EMILIA RIOS SAAVEDRA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1703-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 203,
"rut": "13068925-6",
"candidato": "GONZALO ANDRES VEGA MORENO",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1564-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "EN REDACCION"
},
{
"idx": 204,
"rut": "17697418-4",
"candidato": "TOMAS VODANOVIC ESCUDERO",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1555-2925",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 205,
"rut": "18505235-4",
"candidato": "CAMILA JARPA FERNANDEZ",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1594-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "EN REDACCION"
},
{
"idx": 206,
"rut": "9508652-7",
"candidato": "JULIO SANZANA CARDENAS",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1644-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 207,
"rut": "17238687-3",
"candidato": "EDUARDO JAVIER HERNANDEZ ASTUDILLO",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1553-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 208,
"rut": "19655522-6",
"candidato": "EDUARDO YAÑEZ RIVAS",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1606-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 209,
"rut": "15156187-K",
"candidato": "JAIME BRIONES JORQUERA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1652-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 210,
"rut": "15497676-0",
"candidato": "CRISTIAN SALINAS HERRERA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1653-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 211,
"rut": "7996106-K",
"candidato": "JUAN ENRIQUE LEIVA MADARIAGA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1663-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 212,
"rut": "13412713-9",
"candidato": "FRANCISCO LINCHEO TORREJON",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1664-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "EN REDACCION"
},
{
"idx": 213,
"rut": "9906326-2",
"candidato": "CAROL BOWN SEPÚLVEDA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1290-2025",
"oficio": "NO",
"responsable": "Macarena Barrera",
"estado": "EN REDACCION"
},
{
"idx": 214,
"rut": "18650303-1",
"candidato": "JOSE KRUG OLEA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1596-2025",
"oficio": "NO",
"responsable": "Ximena Valdebenito",
"estado": "EN REDACCION"
},
{
"idx": 215,
"rut": "15042813-0",
"candidato": "ROBINSOSN LAFFERTE CORTES",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "1681-2025",
"oficio": "NO",
"responsable": "Felipe Sarabia",
"estado": "EN REDACCION"
},
{
"idx": 216,
"rut": "13827494-2",
"candidato": "MYRIAM ITURRIETA CRUZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1683-2025",
"oficio": "NO",
"responsable": "Jose Celedon",
"estado": "EN REDACCION"
},
{
"idx": 217,
"rut": "13842924-5",
"candidato": "JOSE SALCEDO CONTRERAS",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1697-2025",
"oficio": "NO",
"responsable": "Genesis Lopez",
"estado": "EN REDACCION"
},
{
"idx": 218,
"rut": "10082335-7",
"candidato": "RICARDO TRIPAINAO",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1295-2025",
"oficio": "NO",
"responsable": "Julissa Lazo",
"estado": "EN REDACCION"
},
{
"idx": 219,
"rut": "12547761-5",
"candidato": "FERNANDO CORREA SANDOVAL",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1459-2025",
"oficio": "NO",
"responsable": "Miguel Baeza",
"estado": "EN REDACCION"
},
{
"idx": 220,
"rut": "10140619-9",
"candidato": "JOSE LUIS FERNANDEZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1305-2025",
"oficio": "NO",
"responsable": "Macarena Barrera",
"estado": "EN REDACCION"
},
{
"idx": 221,
"rut": "13564527-3",
"candidato": "CESAR VEGA LAZO",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1460-2025",
"oficio": "NO",
"responsable": "Ximena Valdebenito",
"estado": "EN REDACCION"
},
{
"idx": 222,
"rut": "15637914-k",
"candidato": "NICOLAS HALABI CORREA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1698-2025",
"oficio": "NO",
"responsable": "Felipe Sarabia",
"estado": "EN REDACCION"
},
{
"idx": 223,
"rut": "11278401-2",
"candidato": "MARIA IGNACIA CASTRO ROJAS",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE PARCIAL",
"causa": "1768-2025",
"oficio": "NO",
"responsable": "Jose Celedon",
"estado": "EN REDACCION"
},
{
"idx": 224,
"rut": "7462917-2",
"candidato": "CARLOS ENRIQUE MANDRIAZA MUÑOZ",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "257-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 225,
"rut": "15185069-3",
"candidato": "CARMEN GLORIA HENRIQUEZ MORENO",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "282-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 226,
"rut": "14518527-0",
"candidato": "CAROLL RIVAS URETA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "280-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 227,
"rut": "10962426-8",
"candidato": "BERTA SOLIS CONTRERAS",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "312-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 228,
"rut": "12379653-5",
"candidato": "PAOLA MARCELA ISLA PEÑAILILLO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "238-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 229,
"rut": "13052629-2",
"candidato": "DENISSE LISETTE CASTILLO NAVARRO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "273-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 230,
"rut": "10155813-4",
"candidato": "EDUVIJIS DELMIRA VASQUEZ COFRE",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "261-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 231,
"rut": "11565964-2",
"candidato": "ALEXIS ARAYA MAUREIRA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "69-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 232,
"rut": "12532551-3",
"candidato": "IVAN LUENGO CASTILLO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "239-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 233,
"rut": "12772684-1",
"candidato": "ANDREA DEL PILAR ESTRADA ARTEAGA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "241-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 234,
"rut": "12643859-1",
"candidato": "JOHNNY YAÑEZ DIAZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "191-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 235,
"rut": "14277741-K",
"candidato": "RUBEN MENDEZ VENEGAS",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "242-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 236,
"rut": "16961991-3",
"candidato": "FERNANDO ANDRES ESPINA PINO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "292-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 237,
"rut": "13082011-5",
"candidato": "FLOR DEL CARMEN ALEÑIR MILLANAO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "194-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 238,
"rut": "13283182-3",
"candidato": "FREDDY BRITO URIBE",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "276-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 239,
"rut": "13692673-K",
"candidato": "PATRICIO BASTIAS GONZALEZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "320-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 240,
"rut": "16825091-6",
"candidato": "GASTON MUÑOZ RIEGO",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "290-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 241,
"rut": "14050926-4",
"candidato": "SEBASTIAN ESTEBAN CABELLO IBARRA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "200-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 242,
"rut": "15305932-2",
"candidato": "HECTOR LUIS SALDIVIA CRUCES",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "283-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 243,
"rut": "11872034-2",
"candidato": "ISMAEL OPAZO BARRA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "269-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 244,
"rut": "15346201-1",
"candidato": "LORENA MARICEL SANDOVAL PUENTES",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "244-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 245,
"rut": "14318120-0",
"candidato": "ELIZABETH ACOSTA VIVEROS",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "137-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 246,
"rut": "15104004-7",
"candidato": "HERNALDO PORTALES CONCHA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "245-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 247,
"rut": "5802658-1",
"candidato": "JUAN NAVARRO VALDERRAMA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "255-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 248,
"rut": "5860849-1",
"candidato": "JUANA CRUZ SANDOVAL ROJAS",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "256-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 249,
"rut": "15390856-7",
"candidato": "CLAUDIA GRICELA MIRANDA CASTRO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "138-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 250,
"rut": "15559070-K",
"candidato": "RUBEN EDUARDO MIRANDA SANHUEZA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "204-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 251,
"rut": "15877331-7",
"candidato": "JUAN GUILLERMO ARTEAGA ARENAS",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "207-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 252,
"rut": "15925188-8",
"candidato": "CONSTANZA FABIOLA VARGAS NUÑEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "141-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 253,
"rut": "10958207-7",
"candidato": "LUIS ALMONACID ALMONACID",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "265-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 254,
"rut": "11620231-K",
"candidato": "MANUEL ALEJANDRO IDUARTE COFRE",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "267-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 255,
"rut": "16498644-6",
"candidato": "NESTOR GAMALIEL ERICES CARRILLO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "247-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 256,
"rut": "12910075-3",
"candidato": "MARIA ANGELICA CRUCES ORREGO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "272-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 257,
"rut": "13097228-4",
"candidato": "MIGUEL ANGEL PEÑA MENESES",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "274-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 258,
"rut": "14053750-0",
"candidato": "MIGUEL SUAZO FUENTES",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "278-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 259,
"rut": "10518649-5",
"candidato": "MONICA GLORIA PATIÑO FERNANDEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "264-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 260,
"rut": "12171788-3",
"candidato": "PATRICIO MONARDES RODRIGUEZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "270-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 261,
"rut": "5519791-1",
"candidato": "GUIDO ALBERTO LILLO GONZALEZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "226-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 262,
"rut": "17758560-2",
"candidato": "NICOL DEL PILAR LEAL FIGUEROA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "214-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 263,
"rut": "17853879-9",
"candidato": "MARIA TERESA BRAVO MATURANA",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "215-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 264,
"rut": "10387122-0",
"candidato": "RAUL ALEJANDRO BUSTAMANTE LLEGUES",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "263-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 265,
"rut": "19463269-K",
"candidato": "NEIL O BRYAMS MEZA ESPINOZA",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "216-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 266,
"rut": "20101941-9",
"candidato": "KAMILA BELEN ALBARRACIN TRONCOSO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "155-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 267,
"rut": "14269193-0",
"candidato": "RAUL ENRIQUE MUÑOZ ACUÑA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "279-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 268,
"rut": "5247988-6",
"candidato": "LUIS RAFAEL MOYANO CRUZ",
"eleccion": "ALCALDE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "170-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 269,
"rut": "13168532-7",
"candidato": "ROXANA NENEN CARCAMO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "275-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 270,
"rut": "6722975-4",
"candidato": "ISIDE RICCI GUTIERREZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "228-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 271,
"rut": "7063221-7",
"candidato": "VICTOR EDUARDO CANTEROS TORRES",
"eleccion": "CORE",
"pronunciamiento": "ACOGE TOTAL",
"causa": "229-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
},
{
"idx": 272,
"rut": "11530215-9",
"candidato": "SANDRA PAOLA MADARIAGA RAMIREZ",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "266-2025",
"oficio": "SI",
"responsable": "Jose Celedon",
"estado": "ENTREGADO"
},
{
"idx": 273,
"rut": "7658966-6",
"candidato": "JOSE MATEO CARRILLO BERMEDO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "230-2025",
"oficio": "SI",
"responsable": "Genesis Lopez",
"estado": "ENTREGADO"
},
{
"idx": 274,
"rut": "9364149-3",
"candidato": "IVAN PATRICIO ARRIAGADA AILLON",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "231-2025",
"oficio": "SI",
"responsable": "Julissa Lazo",
"estado": "ENTREGADO"
},
{
"idx": 275,
"rut": "8813142-8",
"candidato": "CARLOS PINEDA CORTES",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "425-2025",
"oficio": "SI",
"responsable": "Miguel Baeza",
"estado": "ENTREGADO"
},
{
"idx": 276,
"rut": "9925282-0",
"candidato": "LUIS ALBERTO GODOY BIZAMA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "456-2025",
"oficio": "SI",
"responsable": "Macarena Barrera",
"estado": "ENTREGADO"
},
{
"idx": 277,
"rut": "11275475-K",
"candidato": "ANGELICA DEL CARMEN FLORES ROMERO",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "431-2025",
"oficio": "SI",
"responsable": "Ximena Valdebenito",
"estado": "ENTREGADO"
},
{
"idx": 278,
"rut": "14383264-3",
"candidato": "JORGE ARTURO GUTIERREZ GATICA",
"eleccion": "CONCEJAL",
"pronunciamiento": "ACOGE TOTAL",
"causa": "443-2025",
"oficio": "SI",
"responsable": "Felipe Sarabia",
"estado": "ENTREGADO"
}
];
